# Generated by Django 6.0.6 on 2026-06-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('service', models.CharField(choices=[('amc', 'Annual Maintenance Contract (AMC)'), ('network', 'Network Setup / Issues'), ('ipcamera', 'IP Camera'), ('pabx', 'Telephone PABX Solution'), ('webdev', 'Web Development'), ('social', 'Social Media Marketing'), ('apps', 'Apps Development'), ('vat_consult', 'VAT/Tax Consultation'), ('vat_reg', 'VAT Registration'), ('vat_impact', 'VAT Consultancy and Impact Assessment'), ('vat_training', 'VAT Implementation and Training'), ('vat_compliance', 'VAT Accounting and Compliance'), ('vat_returns', 'Filing of VAT Returns'), ('others', 'Others')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
